# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppConeProjectBatch <- function(u, I_lam_eta, m, d, perm12_flat, perm12_offsets, perm22_flat, perm22_offsets, mc4_vec, tup4, init_grid, d_muv, d_mu4) {
    .Call('_mvnMix_cppConeProjectBatch', PACKAGE = 'mvnMix', u, I_lam_eta, m, d, perm12_flat, perm12_offsets, perm22_flat, perm22_offsets, mc4_vec, tup4, init_grid, d_muv, d_mu4)
}

cppMVNmixPMLE <- function(bs, ys, mu0s, sigma0s, m, an, maxit = 2000L, ninits = 10L, tol = 1e-8, tau = 0.5, h = 0L, k = 0L) {
    .Call('_mvnMix_cppMVNmixPMLE', PACKAGE = 'mvnMix', bs, ys, mu0s, sigma0s, m, an, maxit, ninits, tol, tau, h, k)
}

